### ISSUE TITLE
Xiaomi MiPad 4

### ISSUE THREAD

**Issue by alabotski** [WangDaYeeeeee/GeometricWeather#100]
Why I can’t install the application on this device?

**Comment by WangDaYeeeeee** [comment]
Could you send me a screenshot?

Aliaksei Labotski <notifications@github.com> 于 2019年9月29日周日 21:59写道：

**Comment by alabotski** [comment]
No =)

When I try to install with Play Martket

Writes to me
> Product is not compatible with your device

**Comment by alabotski** [comment]
![Screenshot_2019-10-12-23-32-34-352_com android vending](https://user-images.githubusercontent.com/439337/66707416-c4ff3a80-ed48-11e9-859b-ce021b55d20b.png)
Can you fix this error?

**Comment by WangDaYeeeeee** [comment]
I guess it might be because the platform of your device does not meet the
requirements of GeometricWeather, because there is a location widget in the
app, which has certain restrictions on platform of the device. It can be
used only on the arm and x86 platforms. Could you tell me the name of your
device?

Aliaksei Labotski <notifications@github.com> 于2019年10月13日周日 上午4:34写道：

**Comment by alabotski** [comment]
Yes of course

Xiomi Mi Pad 4 64gb lte

**Comment by alabotski** [comment]
Any news?)

**Comment by WangDaYeeeeee** [comment]
Nope, there is no clue at the moment, I will continue to follow up. Sorry
man.

Aliaksei Labotski <notifications@github.com> 于2019年10月25日周五 上午11:33写道：
