### ISSUE TITLE
Feature request - autocompletion

### ISSUE THREAD

**Issue by darrenhaken** [WangDaYeeeeee/GeometricWeather#154]
Would it be possible to add autocompletion when adding locations to the application?

For example as I type Amst it suggests Amsterdam.

**Comment by WangDaYeeeeee** [comment]
Sorry to reply to you so late.

And, I won’t add this feature for the time being. Because I added some different weather sources into GeoWeather. Those sources provide different services, and the user experience in different regions is completely different. I need to ensure the stability of the experience.
