### ISSUE TITLE
Clarifications on permissions

### ISSUE THREAD

**Issue by papjul** [WangDaYeeeeee/GeometricWeather#183]
Hi Wangdaye!

We submitted the app for F-Droid, however we had some feedback regarding some permissions that appear to be unusual for a weather app.

Could you help me clarify them?

* `android.permission.READ_PHONE_STATE`: doesn't seem to be used, to be removed?
* `android.permission.READ_EXTERNAL_STORAGE`: requested when adding widget on Android M and later. However, even if you deny the permission, the widget can still be added and work, so I believe it can be removed?
* `android.permission.WRITE_EXTERNAL_STORAGE`: seems to be used by AMap and Baidu (why?). In that case, I believe it can be moved to the proprietary/AndroidManifest.xml?
* `android.permission.MOUNT_UNMOUNT_FILESYSTEMS`: doesn't seem to be used, to be removed?
* `android.permission.INSTANT_APP_FOREGROUND_SERVICE`: looks like something specific to Google Play Store, can we move it to a specific AndroidManifest-gplay.xml?
* `android.permission.EXPAND_STATUS_BAR`: it is used to create a system tile for weather, correct?

Thanks in advance!

**Comment by WangDaYeeeeee** [comment]
* `android.permission.READ_PHONE_STATE`: This permission is required by Baidu Location SDK and AMap Location SDK components. Since the F-droid version does not include the above 2 SDKs, we should remove this permission.
* `android.permission.READ_EXTERNAL_STORAGE`: This permission is also required by the above 2 location SDKs. At the same time, it seems that this permission is required to obtain wallpaper set by the user?
* `android.permission.WRITE_EXTERNAL_STORAGE`: You're right. It is required by these 2 location SDKs.
* `android.permission.MOUNT_UNMOUNT_FILESYSTEMS`: Also required by 2 location SDKs.
* `android.permission.INSTANT_APP_FOREGROUND_SERVICE`: Yep we can do that.
* `android.permission.EXPAND_STATUS_BAR`: Yeah, when the user clicks on the tile icon in the system drop-down menu, it will jump to the main interface of GeometricWeather. At this time, we need to require this permission to collapse the drop-down menu to make the weather app appear in the foreground.

**Comment by papjul** [comment]
Thank you for your clarifications!

I don't think we need to know (read) what the current wallpaper is, we just overwrite what currently exists?

I also discovered some permissions are added automatically by Dagger, nothing we can do here.

Can you review #184 ?
It removes useless permissions on fdroid build and removes a permission check for widgets on all builds.

**Comment by papjul** [comment]
@WangDaYeeeeee I need an additional clarification on `android.permission.CHANGE_WIFI_STATE`, why would the app need to change the wifi state? Is it actually used?
Thanks!

**Comment by WangDaYeeeeee** [comment]
It's a mistake...

Actually, Baidu location SDK needs this permission. I will put it in the 'proprietary/AndroidManifest.xml'

**Comment by WangDaYeeeeee** [comment]
By the way, I found that I need to request the READ_EXTERNAL_STORAGE permission to read the user's wallpaper, so I added it again.

**Comment by papjul** [comment]
> It's a mistake...
> 
> Actually, Baidu location SDK needs this permission. I will put it in the 'proprietary/AndroidManifest.xml'

Thank you

> By the way, I found that I need to request the READ_EXTERNAL_STORAGE permission to read the user's wallpaper, so I added it again.

Yes, I saw the revert commit, however I don’t understand, I have no issue with the wallpaper, it doesn't need to read the current wallpaper to apply a new one? Is it something specific to some Android devices?

**Comment by WangDaYeeeeee** [comment]
Yes, as you said, it's something specific to some Android devices
