### ISSUE TITLE
Refreshing Geometric Weather freezes my phone (but no my tablet)

### ISSUE THREAD

**Issue by breversa** [WangDaYeeeeee/GeometricWeather#248]
Hello !

Often but not always, refreshing Geometric Weather (by pulling down on the main screen) would start the update process, then slow my phone (not only the app !) down to a crawl and freeze for several minutes (anywhere between 1 to 12), to the point that I often need to power off my phone (LG G4 running /e/ OS 0.17 / Android 9) by pulling the battery out (yes, I *do* have a removable battery :sunglasses: ).

Strangely, it doesn't happen with my tablet (Samsung Galaxy Tab A running LineageOS 17.1 / Android 10).

Here's a changelog I managed to get : https://pastebin.com/3Wm533J5

Please not that this time, my phone did not totally freeze, but Geometric Weather did slow down drastically (the "updating" spinning icon ground to a crawl then stopped).
I'll try to provide more logcats if necessary.

**Comment by papjul** [comment]
Hi,

I don't think something can be done on the app side but here are some things to explore:

1) Make sure you have the latest version of the app (current is 3.013)

2) Try with another weather provider. See if it can be reproduced or if it is something specific to a weather provider

3) Try to disable location services completely + forbid location permission to the app. Add your city manually from the search instead. Check if the issue can be reproduced (specifically, since no one else reported a similar issue, this may be due to a faulty GPS system).

4) Check if you have set custom kernel perf options. Revert to original to see if it fixes it

5) Check if something on your ROM is aggressively killing apps or something. Try allowing the app to run in background

6) As you already know, your phone is no longer supported. You're running a custom ROM which can have issues. Make sure you run the latest version of this custom ROM. If it still doesn't solve the issue, try with latest version of the original vendor ROM (it should be Android Nougat). If you cannot reproduce, then you know it's because of an issue in your custom ROM ;)

**Comment by breversa** [comment]
Hello @papjul and thank you for your generic troubleshooting options ! :)

There's no way I'll ever get back to stock with this (or any) device, but I'll try the weather provider and location services' leads to see if it solves my issue, and will get back to you.

**Comment by breversa** [comment]
After properly deinstalling, cleaning and reinstalling Geometric Weather, my issue went away. Not sure what caused/solved it though, but I'm happy now. Thanks @papjul !
