### ISSUE TITLE
Different informations from same provider

### ISSUE THREAD

**Issue by raphaelgoetter** [WangDaYeeeeee/GeometricWeather#265]
Hello and thank you for this app. I am a big fan of open source and I really appreciate what you are doing.

I have a remark (maybe related to issue #241) about the rain forecast.

I live in France, I use the MétéoFrance provider in the GeometricWeather app.

Geometric often gives me informations that seems contradictory. For example for this afternoon 3PM:

1. Sunny, 20°C
2. 0mm of rainfall
3. 100% chance of rain

<img src="https://user-images.githubusercontent.com/491029/133582829-0b0314fe-61af-4bb0-9e08-ca57665d9d18.jpg" width="400" alt="Geometric app">

How can these three states happen at the same time?

Is it an error of interpretation? of translation?

Meanwhile, for the same place and the same time, the MétéoFrance app gives me the following information:

1. Sunny, 19° C
2. 0mm of rainfall (?)
3. 10% chance of rain

<img src="https://user-images.githubusercontent.com/491029/133582858-008cbd29-01ae-409a-a7a6-b8e4af228514.jpg" width="400" alt="MeteoFrance app">

Why such a difference?

**Comment by papjul** [comment]
Salut Raphaël,

Regarding the temperature, it's currently 19 °C everywhere, I believe data was not recently updated when the screenshot was taken.

Regarding the quantity of precipitation, it's the data that is given to us. I believe it should be read as ≤ 0.1 mm instead of 0 mm, because since the probability is 10 %, it means there is almost no chance there will be at least 0.1 mm of precipitation.

Before digging into precipitation probability, you need to understand it works as a 3 hour or 6 hour timeframe (you will notice precipitation probability is the same for 3 hour straight or 6 hour straight), so it doesn't mean there is 10% precipitation probability between 15:00 and 15:59 but 10% anywhere between 15:00 and 17:59.

So why is there a difference here? It seems it's an issue on our side.

At 15:00, there is a 10% precipitation probability for the next 3 hours... and a 100% precipitation probability for the next 6 hours. So 10% would be more relevant here.

I had trouble making an algorithm when both 3 hour and 6 hour timeframe are given to us. I believe there is an easy fix but I need to throughly test it to avoid downsides. The relevant part of the code: https://github.com/papjul/GeometricWeather/blob/master/app/src/main/java/wangdaye/com/geometricweather/weather/converters/MfResultConverter.java#L501-L542

I will try looking at it in the next few weeks.

**Comment by raphaelgoetter** [comment]
Thank you for your quick feedback and your explanations, I already understand much better the context and the constraints.

> At 15:00, there is a 10% precipitation probability for the next 3 hours... and a 100% precipitation probability for the next 6 hours. So 10% would be more relevant here.

That's what I think too... and this is a priori what is [planned in the code](https://github.com/papjul/GeometricWeather/blob/master/app/src/main/java/wangdaye/com/geometricweather/weather/converters/MfResultConverter.java#L526), right?

In any case thank you very much for your participation in this project, and Vive la France! :p

**Comment by papjul** [comment]
> That's what I think too... and this is a priori what is [planned in the code](https://github.com/papjul/GeometricWeather/blob/master/app/src/main/java/wangdaye/com/geometricweather/weather/converters/MfResultConverter.java#L526), right?

The issue doesn't happen here but on L512-513. L526 is for h+3, h+4, h+5 and L513 is for h+0, h+1, h+2. In our case, the 100% probability for the next 6 hours is at 15:00 (so h+0).

The fix is probably to replace "if" with "else if" to take the 3 hour value if it's available, and not take the 6 hour one if the 3 hour is available, but I ABSOLUTELY need to test it doesn't cause side effects.
