### ISSUE TITLE
Fdroid download broken

### ISSUE THREAD

**Issue by GEkuL** [WangDaYeeeeee/GeometricWeather#316]
Hi there,
I can't upload the update v 3.100 on Fdroid. 
When checking the [site](https://f-droid.org/en/packages/wangdaye.com.geometricweather/), there're no version updates from v 3.013 (2021-04-18)

Could you fix the trouble please?

**Comment by papjul** [comment]
Hi, F-Droid removed the version due to #307 (crash when upgrading with a widget installed).

We are not involved with the decision, please report to them if you need to.

Regarding this repo, all 3 variants (F-Droid, Google Play, public) are provided in [Releases](https://github.com/WangDaYeeeeee/GeometricWeather/releases), but with different keys than F-Droid'.

**Comment by GEkuL** [comment]
@papjul thanks for the swift reply!
So will there be a fix of the issue?

**Comment by papjul** [comment]
There have been a couple of commits after 3.100, I don't know if they fix the issue, please follow #307

**Comment by GEkuL** [comment]
@papjul 
thanks!
