### ISSUE TITLE
OpenWeatherMap - "Precipitation" disappeared from hourly forecast 

### ISSUE THREAD

**Issue by ghost** [WangDaYeeeeee/GeometricWeather#405]
Version: 3.102_fdroid
Provider: OpenWeatherMap
Phone: Xiaomi Mi 9T Pro
ROM: LineageOS 17.1 (Android 10)

Hello,

I installed the app recently (around a week ago) and use OpenWeatherMap as AccuWeather is inaccurate in my location.
Since yesterday, the precipitation is not showing any longer from the hourly forecast, though it is still visible in the daily one.

What I did:
- check if precipitation was still in the display hourly trend
- restart the app
- remove the API key, the location, restart the app and put both back

Do you know what can be the cause?

Thank you!

PS: great app btw!

![Screenshot_20220821-114847_Geometric_Weather](https://user-images.githubusercontent.com/62804718/185785394-cbe0f08e-9bd0-48df-9831-611464d4d457.png)

**Comment by sheltpat** [comment]
That's because there is no precipitation forecast within the apps timeframe. In other words, there is no rain in sight, so the button is obsolete and vanishes temporarily.
It will reappear when there is actual precipitation within the hourly forecast.

I don't know if that is intentional, but I guess there is no point in having a button when there is nothing to be seen anyway.

**Comment by ghost** [comment]
Hi sheltpat,
Thank you for your response.
I am a bit surprised because the image was showing rain at 11:00 on the screeshot above. But in the meantime, it is also written that there should be no precipitation for at least the next 120 minutes…
Anyway, I will close this issue and re-open if it would turn out that the precipitation doesn't show up again.
Thanks!
