### ISSUE TITLE
Swap day and month in spanish

### ISSUE THREAD

**Issue by Llanerosolitario37** [WangDaYeeeeee/GeometricWeather#485]
Hi all,
Thanks for this great weather app, I'm from Spain and I would like that in the daily weather could be swapped the day by month, now is showed first the month.
Many thanks.

**Comment by papjul** [comment]
This is how the Spanish translator decided to translate day and month. If this is an error, you can edit the translation file, otherwise please make a regional variant.

Impacted strings are here:
https://github.com/WangDaYeeeeee/GeometricWeather/blob/master/app/src/main/res/values-es/strings.xml#L151-L155

**Comment by Llanerosolitario37** [comment]
Many thanks.

**Comment by Llanerosolitario37** [comment]
Many thanks!
